In [6]:
from pathlib import Path
import pandas as pd

#Make sure to verify the path of the file, in this case is like this 
#But I recomend you to check it before any error

BASE_DIR = Path.cwd().parent.parent

RAW_DATA_PATH = BASE_DIR / "data" / "raw"

print(RAW_DATA_PATH)
print(RAW_DATA_PATH.exists())

csv_files = list(RAW_DATA_PATH.glob("*.csv"))

print(csv_files)

c:\Users\yeanm\Downloads\Quinto\ETL\3\WS\World-Happiness\data\raw
True
[WindowsPath('c:/Users/yeanm/Downloads/Quinto/ETL/3/WS/World-Happiness/data/raw/2015.csv'), WindowsPath('c:/Users/yeanm/Downloads/Quinto/ETL/3/WS/World-Happiness/data/raw/2016.csv'), WindowsPath('c:/Users/yeanm/Downloads/Quinto/ETL/3/WS/World-Happiness/data/raw/2017.csv'), WindowsPath('c:/Users/yeanm/Downloads/Quinto/ETL/3/WS/World-Happiness/data/raw/2018.csv'), WindowsPath('c:/Users/yeanm/Downloads/Quinto/ETL/3/WS/World-Happiness/data/raw/2019.csv')]

In [7]:
from pathlib import Path
import pandas as pd


BASE_DIR = Path.cwd().parent.parent

RAW_DATA_PATH = BASE_DIR / "data" / "raw"

def get_csv_files():
    """
    Get all CSV files from raw data directory.
    """

    csv_files = list(RAW_DATA_PATH.glob("*.csv"))

    if not csv_files:
        raise FileNotFoundError(
            f"No CSV files found in {RAW_DATA_PATH}"
        )

    return csv_files


def extract_single_file(file_path):
    """
    Extract a single CSV file into a DataFrame.
    """

    try:
        df = pd.read_csv(file_path)

        # Extract year from filename
        df["year"] = file_path.stem

        return df

    except Exception as e:
        print(f"[ERROR] Failed loading {file_path.name}")
        print(e)

        return None


def extract_all_data():
    """
    Extract all CSV datasets.
    """

    csv_files = get_csv_files()

    datasets = {}

    for file in csv_files:

        df = extract_single_file(file)

        if df is not None:
            datasets[file.stem] = df

    return datasets


if __name__ == "__main__":

    data = extract_all_data()

    df_2015 = data["2015"]

    df_2016 = data["2016"]

    df_2017 = data["2017"]

    df_2018 = data["2018"]

    df_2019 = data["2019"]

    for year, df in data.items():
        print("\n")
        print(f"Dataset Year: {year}")
        print(df.head())

Dataset Year: 2015
       country          Region  Happiness_rank  Happiness_score  \
0  Switzerland  Western Europe               1            7.587
1      Iceland  Western Europe               2            7.561
2      Denmark  Western Europe               3            7.527
3       Norway  Western Europe               4            7.522
4       Canada   North America               5            7.427

   Standard Error      gdp   family   health  freedom    trust  generosity  \
0         0.03411  1.39651  1.34951  0.94143  0.66557  0.41978     0.29678
1         0.04884  1.30232  1.40223  0.94784  0.62877  0.14145     0.43630
2         0.03328  1.32548  1.36058  0.87464  0.64938  0.48357     0.34139
3         0.03880  1.45900  1.33095  0.88521  0.66973  0.36503     0.34699
4         0.03553  1.32629  1.32261  0.90563  0.63297  0.32957     0.45811

   Dystopia Residual  year
0            2.51738  2015
1            2.70201  2015
2            2.49204  2015
3            2.46531  2015
4            2.45176  2015


Dataset Year: 2016
       country          Region  Happiness_rank  Happiness_score  \
0      Denmark  Western Europe               1            7.526
1  Switzerland  Western Europe               2            7.509
2      Iceland  Western Europe               3            7.501
3       Norway  Western Europe               4            7.498
4      Finland  Western Europe               5            7.413

   Lower Confidence Interval  Upper Confidence Interval      gdp   family  \
0                      7.460                      7.592  1.44178  1.16374
1                      7.428                      7.590  1.52733  1.14524
2                      7.333                      7.669  1.42666  1.18326
3                      7.421                      7.575  1.57744  1.12690
4                      7.351                      7.475  1.40598  1.13464

    health  freedom    trust  generosity  Dystopia Residual  year
0  0.79504  0.57941  0.44453     0.36171            2.73939  2016
1  0.86303  0.58557  0.41203     0.28083            2.69463  2016
2  0.86733  0.56624  0.14975     0.47678            2.83137  2016
3  0.79579  0.59609  0.35776     0.37895            2.66465  2016
4  0.81091  0.57104  0.41004     0.25492            2.82596  2016


Dataset Year: 2017
       country  Happiness_rank  Happiness_score  Whisker.high  Whisker.low  \
0       Norway               1            7.537      7.594445     7.479556
1      Denmark               2            7.522      7.581728     7.462272
2      Iceland               3            7.504      7.622030     7.385970
3  Switzerland               4            7.494      7.561772     7.426227
4      Finland               5            7.469      7.527542     7.410458

        gdp    family    health   freedom  generosity     trust  \
0  1.616463  1.533524  0.796667  0.635423    0.362012  0.315964
1  1.482383  1.551122  0.792566  0.626007    0.355280  0.400770
2  1.480633  1.610574  0.833552  0.627163    0.475540  0.153527
3  1.564980  1.516912  0.858131  0.620071    0.290549  0.367007
4  1.443572  1.540247  0.809158  0.617951    0.245483  0.382612

   Dystopia.Residual  year
0           2.277027  2017
1           2.313707  2017
2           2.322715  2017
3           2.276716  2017
4           2.430182  2017


Dataset Year: 2018
   Happiness_rank      country  Happiness_score    gdp  family  health  \
0               1      Finland            7.632  1.305   1.592   0.874
1               2       Norway            7.594  1.456   1.582   0.861
2               3      Denmark            7.555  1.351   1.590   0.868
3               4      Iceland            7.495  1.343   1.644   0.914
4               5  Switzerland            7.487  1.420   1.549   0.927

   freedom  generosity  trust  year
0    0.681       0.202  0.393  2018
1    0.686       0.286  0.340  2018
2    0.683       0.284  0.408  2018
3    0.677       0.353  0.138  2018
4    0.660       0.256  0.357  2018


Dataset Year: 2019
   Happiness_rank      country  Happiness_score    gdp  family  health  \
0               1      Finland            7.769  1.340   1.587   0.986
1               2      Denmark            7.600  1.383   1.573   0.996
2               3       Norway            7.554  1.488   1.582   1.028
3               4      Iceland            7.494  1.380   1.624   1.026
4               5  Netherlands            7.488  1.396   1.522   0.999

   freedom  generosity  trust  year
0    0.596       0.153  0.393  2019
1    0.592       0.252  0.410  2019
2    0.603       0.271  0.341  2019
3    0.591       0.354  0.118  2019
4    0.557       0.322  0.298  2019

In [8]:
def cleaning(df):

    # Drop unnecessary columns
    columns_to_drop = [
        "Region",
        "Standard Error",
        "Lower Confidence Interval",
        "Upper Confidence Interval",
        "Whisker.high",
        "Whisker.low",
        "Dystopia Residual",
        "Dystopia.Residual"
    ]

    existing_columns = [
        col for col in columns_to_drop
        if col in df.columns
    ]

    C2015 = df_2015.drop(columns=existing_columns)

    C2016 = df_2016.drop(columns=existing_columns)

    C2017 = df_2017.drop(columns=existing_columns)

    C2018 = df_2018.drop(columns=existing_columns)

    C2019 = df_2019.drop(columns=existing_columns)
    
    dfs = [
        C2015,
        C2016,
        C2017,
        C2018,
        C2019   
    ]

    unified_df = pd.concat(
    dfs,
    ignore_index=False
    )

    return df, dfs, unified_df, C2015, C2016, C2017, C2018, C2019

In [9]:

    # Drop unnecessary columns
columns_to_drop = [
        "Region",
        "Standard Error",
        "Lower Confidence Interval",
        "Upper Confidence Interval",
        "Whisker.high",
        "Whisker.low",
        "Dystopia Residual",
        "Dystopia.Residual"
    ]

existing_columns2015 = [
        col for col in columns_to_drop
        if col in df_2015.columns
    ]
C2015 = df_2015.drop(columns=existing_columns2015)

existing_columns2016 = [
        col for col in columns_to_drop
        if col in df_2016.columns
    ]
C2016 = df_2016.drop(columns=existing_columns2016)

existing_columns2017 = [
        col for col in columns_to_drop
        if col in df_2017.columns
    ]
C2017 = df_2017.drop(columns=existing_columns2017)

existing_columns2018 = [
        col for col in columns_to_drop
        if col in df_2018.columns
    ]
C2018 = df_2018.drop(columns=existing_columns2018)

existing_columns2019 = [
        col for col in columns_to_drop
        if col in df_2019.columns
    ]
C2019 = df_2019.drop(columns=existing_columns2019)
    
dfs = [
        C2015,
        C2016,
        C2017,
        C2018,
        C2019   
    ]

unified_df = pd.concat(
    dfs,
    ignore_index=True
    )


print(unified_df.shape)

unified_df

(782, 10)

,country,Happiness_rank,Happiness_score,gdp,family,health,freedom,trust,generosity,year
0,Switzerland,1,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2015
1,Iceland,2,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2015
2,Denmark,3,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2015
3,Norway,4,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2015
4,Canada,5,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2015
...,...,...,...,...,...,...,...,...,...,...
777,Rwanda,152,3.334,0.35900,0.71100,0.61400,0.55500,0.41100,0.21700,2019
778,Tanzania,153,3.231,0.47600,0.88500,0.49900,0.41700,0.14700,0.27600,2019
779,Afghanistan,154,3.203,0.35000,0.51700,0.36100,0.00000,0.02500,0.15800,2019
780,Central African Republic,155,3.083,0.02600,0.00000,0.10500,0.22500,0.03500,0.23500,2019
781,South Sudan,156,2.853,0.30600,0.57500,0.29500,0.01000,0.09100,0.20200,2019

In [11]:
unified_df[
    unified_df["gdp"] == 0
]

,country,Happiness_rank,Happiness_score,gdp,family,health,freedom,trust,generosity,year
119,Congo (Kinshasa),120,4.517,0.0,1.00120,0.098060,0.226050,0.076250,0.248340,2015
233,Somalia,76,5.440,0.0,0.33613,0.114660,0.567780,0.311800,0.272250,2016
469,Central African Republic,155,2.693,0.0,0.00000,0.018773,0.270842,0.056565,0.280876,2017
567,Somalia,98,4.982,0.0,0.71200,0.115000,0.674000,0.282000,0.238000,2018
737,Somalia,112,4.668,0.0,0.69800,0.268000,0.559000,0.270000,0.243000,2019